package ma.okteam.galopia.view.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

/**
 * ChevalRobe generated by hbm2java
 */
public class ChevalRobeBean extends OwaspBean<Integer> implements java.io.Serializable {

	private String libelle;
	private List<ChevalBean> chevals = new ArrayList<ChevalBean>(0);

	public ChevalRobeBean() {
	}

	public ChevalRobeBean(String libelle, List<ChevalBean> chevals) {
		this.libelle = libelle;
		this.chevals = chevals;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public List<ChevalBean> getChevals() {
		return this.chevals;
	}

	public void setChevals(List<ChevalBean> chevals) {
		this.chevals = chevals;
	}

}
