package ma.okteam.galopia.view.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Club generated by hbm2java
 */
public class ClubBean extends OwaspBean<Integer> implements java.io.Serializable {

	private ClubTypeBean clubType;
	private String nom;
	private String adresse;
	private String codePostal;
	private String telephone;
	private String email;
	private List<AdherentBean> adherents = new ArrayList<AdherentBean>(0);

	public ClubBean() {
	}

	public ClubBean(ClubTypeBean clubType, String nom, String adresse,
			String codePostal, String telephone, String email,
			List<AdherentBean> adherents) {
		this.clubType = clubType;
		this.nom = nom;
		this.adresse = adresse;
		this.codePostal = codePostal;
		this.telephone = telephone;
		this.email = email;
		this.adherents = adherents;
	}


	public ClubTypeBean getClubType() {
		return this.clubType;
	}

	public void setClubType(ClubTypeBean clubType) {
		this.clubType = clubType;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public List<AdherentBean> getAdherents() {
		return this.adherents;
	}

	public void setAdherents(List<AdherentBean> adherents) {
		this.adherents = adherents;
	}

}
