package ma.okteam.galopia.view.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

/**
 * ClubType generated by hbm2java
 */
public class ClubTypeBean extends OwaspBean<Integer> implements java.io.Serializable {

	private String libelle;
	private List<ClubBean> clubs = new ArrayList<ClubBean>(0);

	public ClubTypeBean() {
	}

	public ClubTypeBean(String libelle, List<ClubBean> clubs) {
		this.libelle = libelle;
		this.clubs = clubs;
	}


	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public List<ClubBean> getClubs() {
		return this.clubs;
	}

	public void setClubs(List<ClubBean> clubs) {
		this.clubs = clubs;
	}

}
