package ma.okteam.galopia.view.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Cours generated by hbm2java
 */
public class CoursBean extends OwaspBean<Integer> implements java.io.Serializable {

	private AdherentBean adherent;
	private String nom;
	private String description;
	private Integer jour;
	private Date heure;
	private Integer maxParticipant;
	private List<InstanceBean> instances = new ArrayList<InstanceBean>(0);

	public CoursBean() {
	}

	public CoursBean(AdherentBean adherent, String nom, String description,
			Integer jour, Date heure, Integer maxParticipant,
			List<InstanceBean> instances) {
		this.adherent = adherent;
		this.nom = nom;
		this.description = description;
		this.jour = jour;
		this.heure = heure;
		this.maxParticipant = maxParticipant;
		this.instances = instances;
	}

	public AdherentBean getAdherent() {
		return this.adherent;
	}

	public void setAdherent(AdherentBean adherent) {
		this.adherent = adherent;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getJour() {
		return this.jour;
	}

	public void setJour(Integer jour) {
		this.jour = jour;
	}

	public Date getHeure() {
		return this.heure;
	}

	public void setHeure(Date heure) {
		this.heure = heure;
	}

	public Integer getMaxParticipant() {
		return this.maxParticipant;
	}

	public void setMaxParticipant(Integer maxParticipant) {
		this.maxParticipant = maxParticipant;
	}

	public List<InstanceBean> getInstances() {
		return this.instances;
	}

	public void setInstances(List<InstanceBean> instances) {
		this.instances = instances;
	}

}
