package ma.okteam.galopia.view.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Instance generated by hbm2java
 */
public class InstanceBean extends OwaspBean<Integer> implements java.io.Serializable {

	private CoursBean cours;
	private Date dateInstance;
	private Integer maxParticipant;
	private List<InstanceCommentaireBean> instanceCommentaires = new ArrayList<InstanceCommentaireBean>(
			0);
	private List<AdherentInstanceBean> adherentInstances = new ArrayList<AdherentInstanceBean>(
			0);

	public InstanceBean() {
	}

	public InstanceBean(CoursBean cours, Date dateInstance, Integer maxParticipant,
			List<InstanceCommentaireBean> instanceCommentaires,
			List<AdherentInstanceBean> adherentInstances) {
		this.cours = cours;
		this.dateInstance = dateInstance;
		this.maxParticipant = maxParticipant;
		this.instanceCommentaires = instanceCommentaires;
		this.adherentInstances = adherentInstances;
	}


	public CoursBean getCours() {
		return this.cours;
	}

	public void setCours(CoursBean cours) {
		this.cours = cours;
	}

	public Date getDateInstance() {
		return this.dateInstance;
	}

	public void setDateInstance(Date dateInstance) {
		this.dateInstance = dateInstance;
	}

	public Integer getMaxParticipant() {
		return this.maxParticipant;
	}

	public void setMaxParticipant(Integer maxParticipant) {
		this.maxParticipant = maxParticipant;
	}

	public List<InstanceCommentaireBean> getInstanceCommentaires() {
		return this.instanceCommentaires;
	}

	public void setInstanceCommentaires(
			List<InstanceCommentaireBean> instanceCommentaires) {
		this.instanceCommentaires = instanceCommentaires;
	}

	public List<AdherentInstanceBean> getAdherentInstances() {
		return this.adherentInstances;
	}

	public void setAdherentInstances(List<AdherentInstanceBean> adherentInstances) {
		this.adherentInstances = adherentInstances;
	}

}
