package ma.okteam.galopia.view.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * InstanceCommentaire generated by hbm2java
 */
public class InstanceCommentaireBean extends OwaspBean<Integer> implements java.io.Serializable {

	private AdherentBean adherent;
	private InstanceBean instance;
	private InstanceCommentaireBean instanceCommentaire;
	private String commentaire;
	private Date datePublication;
	private List<InstanceCommentaireBean> instanceCommentaires = new ArrayList<InstanceCommentaireBean>(
			0);

	public InstanceCommentaireBean() {
	}

	public InstanceCommentaireBean(AdherentBean adherent, InstanceBean instance,
			InstanceCommentaireBean instanceCommentaire, String commentaire,
			Date datePublication, List<InstanceCommentaireBean> instanceCommentaires) {
		this.adherent = adherent;
		this.instance = instance;
		this.instanceCommentaire = instanceCommentaire;
		this.commentaire = commentaire;
		this.datePublication = datePublication;
		this.instanceCommentaires = instanceCommentaires;
	}


	public AdherentBean getAdherent() {
		return this.adherent;
	}

	public void setAdherent(AdherentBean adherent) {
		this.adherent = adherent;
	}

	public InstanceBean getInstance() {
		return this.instance;
	}

	public void setInstance(InstanceBean instance) {
		this.instance = instance;
	}

	public InstanceCommentaireBean getInstanceCommentaire() {
		return this.instanceCommentaire;
	}

	public void setInstanceCommentaire(InstanceCommentaireBean instanceCommentaire) {
		this.instanceCommentaire = instanceCommentaire;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public Date getDatePublication() {
		return this.datePublication;
	}

	public void setDatePublication(Date datePublication) {
		this.datePublication = datePublication;
	}

	public List<InstanceCommentaireBean> getInstanceCommentaires() {
		return this.instanceCommentaires;
	}

	public void setInstanceCommentaires(
			List<InstanceCommentaireBean> instanceCommentaires) {
		this.instanceCommentaires = instanceCommentaires;
	}

}
