package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Adherent generated by hbm2java
 */
@Entity
@Table(name = "ADHERENT")
public class Adherent implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String prenom;
	private String email;
	private String adresse;
	private String codePostal;
	private String telephone;
	private Date dateNaissance;
	private Set<Club> clubs = new HashSet<Club>(0);
	private Set<AdherentInstance> adherentInstances = new HashSet<AdherentInstance>(
			0);
	private Set<Cheval> chevals = new HashSet<Cheval>(0);
	private Set<InstanceCommentaire> instanceCommentaires = new HashSet<InstanceCommentaire>(
			0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Cours> courses = new HashSet<Cours>(0);

	public Adherent() {
	}

	public Adherent(String nom, String prenom, String email, String adresse,
			String codePostal, String telephone, Date dateNaissance,
			Set<Club> clubs, Set<AdherentInstance> adherentInstances,
			Set<Cheval> chevals, Set<InstanceCommentaire> instanceCommentaires,
			Set<User> users, Set<Cours> courses) {
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.adresse = adresse;
		this.codePostal = codePostal;
		this.telephone = telephone;
		this.dateNaissance = dateNaissance;
		this.clubs = clubs;
		this.adherentInstances = adherentInstances;
		this.chevals = chevals;
		this.instanceCommentaires = instanceCommentaires;
		this.users = users;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADRESSE")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "CODE_POSTAL", length = 5)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "TELEPHONE", length = 64)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISSANCE", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ADHERENT_CLUB", joinColumns = { @JoinColumn(name = "ADHERENT_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CLUB_ID", nullable = false, updatable = false) })
	public Set<Club> getClubs() {
		return this.clubs;
	}

	public void setClubs(Set<Club> clubs) {
		this.clubs = clubs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adherent")
	public Set<AdherentInstance> getAdherentInstances() {
		return this.adherentInstances;
	}

	public void setAdherentInstances(Set<AdherentInstance> adherentInstances) {
		this.adherentInstances = adherentInstances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adherent")
	public Set<Cheval> getChevals() {
		return this.chevals;
	}

	public void setChevals(Set<Cheval> chevals) {
		this.chevals = chevals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adherent")
	public Set<InstanceCommentaire> getInstanceCommentaires() {
		return this.instanceCommentaires;
	}

	public void setInstanceCommentaires(
			Set<InstanceCommentaire> instanceCommentaires) {
		this.instanceCommentaires = instanceCommentaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adherent")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adherent")
	public Set<Cours> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Cours> courses) {
		this.courses = courses;
	}

}
