package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdherentInstanceId generated by hbm2java
 */
@Embeddable
public class AdherentInstanceId implements java.io.Serializable {

	private int adhrentId;
	private int instanceId;
	private int chevalId;

	public AdherentInstanceId() {
	}

	public AdherentInstanceId(int adhrentId, int instanceId, int chevalId) {
		this.adhrentId = adhrentId;
		this.instanceId = instanceId;
		this.chevalId = chevalId;
	}

	@Column(name = "ADHRENT_ID", nullable = false)
	public int getAdhrentId() {
		return this.adhrentId;
	}

	public void setAdhrentId(int adhrentId) {
		this.adhrentId = adhrentId;
	}

	@Column(name = "INSTANCE_ID", nullable = false)
	public int getInstanceId() {
		return this.instanceId;
	}

	public void setInstanceId(int instanceId) {
		this.instanceId = instanceId;
	}

	@Column(name = "CHEVAL_ID", nullable = false)
	public int getChevalId() {
		return this.chevalId;
	}

	public void setChevalId(int chevalId) {
		this.chevalId = chevalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdherentInstanceId))
			return false;
		AdherentInstanceId castOther = (AdherentInstanceId) other;

		return (this.getAdhrentId() == castOther.getAdhrentId())
				&& (this.getInstanceId() == castOther.getInstanceId())
				&& (this.getChevalId() == castOther.getChevalId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAdhrentId();
		result = 37 * result + this.getInstanceId();
		result = 37 * result + this.getChevalId();
		return result;
	}

}
