package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cheval generated by hbm2java
 */
@Entity
@Table(name = "CHEVAL")
public class Cheval implements java.io.Serializable {

	private Integer id;
	private ChevalCategory chevalCategory;
	private Adherent adherent;
	private ChevalRobe chevalRobe;
	private String nom;
	private Date dateNaissance;
	private Boolean sexe;
	private Set<AdherentInstance> adherentInstances = new HashSet<AdherentInstance>(
			0);

	public Cheval() {
	}

	public Cheval(ChevalCategory chevalCategory, Adherent adherent,
			ChevalRobe chevalRobe, String nom, Date dateNaissance,
			Boolean sexe, Set<AdherentInstance> adherentInstances) {
		this.chevalCategory = chevalCategory;
		this.adherent = adherent;
		this.chevalRobe = chevalRobe;
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.sexe = sexe;
		this.adherentInstances = adherentInstances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORIE_ID")
	public ChevalCategory getChevalCategory() {
		return this.chevalCategory;
	}

	public void setChevalCategory(ChevalCategory chevalCategory) {
		this.chevalCategory = chevalCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROPRIETAIRE_ID")
	public Adherent getAdherent() {
		return this.adherent;
	}

	public void setAdherent(Adherent adherent) {
		this.adherent = adherent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROBE_ID")
	public ChevalRobe getChevalRobe() {
		return this.chevalRobe;
	}

	public void setChevalRobe(ChevalRobe chevalRobe) {
		this.chevalRobe = chevalRobe;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISSANCE", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "SEXE")
	public Boolean getSexe() {
		return this.sexe;
	}

	public void setSexe(Boolean sexe) {
		this.sexe = sexe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cheval")
	public Set<AdherentInstance> getAdherentInstances() {
		return this.adherentInstances;
	}

	public void setAdherentInstances(Set<AdherentInstance> adherentInstances) {
		this.adherentInstances = adherentInstances;
	}

}
