package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChevalCategory generated by hbm2java
 */
@Entity
@Table(name = "CHEVAL_CATEGORY")
public class ChevalCategory implements java.io.Serializable {

	private Integer id;
	private String code;
	private Set<Cheval> chevals = new HashSet<Cheval>(0);

	public ChevalCategory() {
	}

	public ChevalCategory(String code, Set<Cheval> chevals) {
		this.code = code;
		this.chevals = chevals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CODE", length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chevalCategory")
	public Set<Cheval> getChevals() {
		return this.chevals;
	}

	public void setChevals(Set<Cheval> chevals) {
		this.chevals = chevals;
	}

}
