package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Club generated by hbm2java
 */
@Entity
@Table(name = "CLUB")
public class Club implements java.io.Serializable {

	private Integer id;
	private ClubType clubType;
	private String nom;
	private String adresse;
	private String codePostal;
	private String telephone;
	private String email;
	private Set<Adherent> adherents = new HashSet<Adherent>(0);

	public Club() {
	}

	public Club(ClubType clubType, String nom, String adresse,
			String codePostal, String telephone, String email,
			Set<Adherent> adherents) {
		this.clubType = clubType;
		this.nom = nom;
		this.adresse = adresse;
		this.codePostal = codePostal;
		this.telephone = telephone;
		this.email = email;
		this.adherents = adherents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLUB_TYPE_ID")
	public ClubType getClubType() {
		return this.clubType;
	}

	public void setClubType(ClubType clubType) {
		this.clubType = clubType;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "ADRESSE")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "CODE_POSTAL")
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "TELEPHONE", length = 64)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ADHERENT_CLUB", joinColumns = { @JoinColumn(name = "CLUB_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ADHERENT_ID", nullable = false, updatable = false) })
	public Set<Adherent> getAdherents() {
		return this.adherents;
	}

	public void setAdherents(Set<Adherent> adherents) {
		this.adherents = adherents;
	}

}
