package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Instance generated by hbm2java
 */
@Entity
@Table(name = "INSTANCE")
public class Instance implements java.io.Serializable {

	private Integer id;
	private Cours cours;
	private Date dateInstance;
	private Integer maxParticipant;
	private Set<InstanceCommentaire> instanceCommentaires = new HashSet<InstanceCommentaire>(
			0);
	private Set<AdherentInstance> adherentInstances = new HashSet<AdherentInstance>(
			0);

	public Instance() {
	}

	public Instance(Cours cours, Date dateInstance, Integer maxParticipant,
			Set<InstanceCommentaire> instanceCommentaires,
			Set<AdherentInstance> adherentInstances) {
		this.cours = cours;
		this.dateInstance = dateInstance;
		this.maxParticipant = maxParticipant;
		this.instanceCommentaires = instanceCommentaires;
		this.adherentInstances = adherentInstances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURS_ID")
	public Cours getCours() {
		return this.cours;
	}

	public void setCours(Cours cours) {
		this.cours = cours;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_INSTANCE", length = 26)
	public Date getDateInstance() {
		return this.dateInstance;
	}

	public void setDateInstance(Date dateInstance) {
		this.dateInstance = dateInstance;
	}

	@Column(name = "MAX_PARTICIPANT")
	public Integer getMaxParticipant() {
		return this.maxParticipant;
	}

	public void setMaxParticipant(Integer maxParticipant) {
		this.maxParticipant = maxParticipant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instance")
	public Set<InstanceCommentaire> getInstanceCommentaires() {
		return this.instanceCommentaires;
	}

	public void setInstanceCommentaires(
			Set<InstanceCommentaire> instanceCommentaires) {
		this.instanceCommentaires = instanceCommentaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instance")
	public Set<AdherentInstance> getAdherentInstances() {
		return this.adherentInstances;
	}

	public void setAdherentInstances(Set<AdherentInstance> adherentInstances) {
		this.adherentInstances = adherentInstances;
	}

}
