package ma.okteam.galopia.persistance.model;

// Generated 2 juil. 2017 16:02:51 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstanceCommentaire generated by hbm2java
 */
@Entity
@Table(name = "INSTANCE_COMMENTAIRE")
public class InstanceCommentaire implements java.io.Serializable {

	private Integer id;
	private Adherent adherent;
	private Instance instance;
	private InstanceCommentaire instanceCommentaire;
	private String commentaire;
	private Date datePublication;
	private Set<InstanceCommentaire> instanceCommentaires = new HashSet<InstanceCommentaire>(
			0);

	public InstanceCommentaire() {
	}

	public InstanceCommentaire(Adherent adherent, Instance instance,
			InstanceCommentaire instanceCommentaire, String commentaire,
			Date datePublication, Set<InstanceCommentaire> instanceCommentaires) {
		this.adherent = adherent;
		this.instance = instance;
		this.instanceCommentaire = instanceCommentaire;
		this.commentaire = commentaire;
		this.datePublication = datePublication;
		this.instanceCommentaires = instanceCommentaires;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADHERENT_ID")
	public Adherent getAdherent() {
		return this.adherent;
	}

	public void setAdherent(Adherent adherent) {
		this.adherent = adherent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTANCE_ID")
	public Instance getInstance() {
		return this.instance;
	}

	public void setInstance(Instance instance) {
		this.instance = instance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMMENTAIRE_ID")
	public InstanceCommentaire getInstanceCommentaire() {
		return this.instanceCommentaire;
	}

	public void setInstanceCommentaire(InstanceCommentaire instanceCommentaire) {
		this.instanceCommentaire = instanceCommentaire;
	}

	@Column(name = "COMMENTAIRE", length = 2048)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_PUBLICATION", length = 26)
	public Date getDatePublication() {
		return this.datePublication;
	}

	public void setDatePublication(Date datePublication) {
		this.datePublication = datePublication;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instanceCommentaire")
	public Set<InstanceCommentaire> getInstanceCommentaires() {
		return this.instanceCommentaires;
	}

	public void setInstanceCommentaires(
			Set<InstanceCommentaire> instanceCommentaires) {
		this.instanceCommentaires = instanceCommentaires;
	}

}
